### ISSUE TITLE
Where are the smart contracts themselves?

### ISSUE THREAD

**Issue by zigomi** [NishantChandla/nft-marketplace-tutorial#1]
Where are the smart contracts themselves?

**Comment by NishantChandla** [comment]
Hey @zigomi,
You can checkout the contract breakdown [here](https://learn.figment.io/tutorials/create-an-nft-marketplace-on-tezos).
Complete smart contracts [here](https://smartpy.io/ide?cid=QmVGqtBwNNnxwdFPrnmZYnQGq5PEQGSGMQwrB53rMtuJfg&k=6c6a8bdfdaf5a2893854)
