### ISSUE TITLE
Profile Page - Help

### ISSUE THREAD

**Issue by discotest** [NishantChandla/nft-marketplace-tutorial#2]
Hello there mr. Nishant! This is João. I just emailed you, but maybe here is quicker :smile: 
It's an honour to be here speaking to you.

I've been following your Tezos marketplace tutorial for some time, learning a lot with your knowledge.

I managed to get it working and it's beautiful.

Now I'm trying to integrate a "profile page", a page where you could see only the NFTs someone made. But I've been having a lot of difficulty on it. I'd appreciate some help on it. 

For now i see under the actions we call the contract storage via the TZKT indexer API, but how do I actually filter them only by a wallet/creator/collector ? Also, how do I set them in a specific separate dynamic page?

A secondary question is - what If I want to make my NFT to have multiple editions?

Thanks for the open knowledge and the opportunity, still the best tutorial ever made on the subject.
I hope we can connect and chat soon! ✌

João Pedro,
Tezos learner

**Comment by NishantChandla** [comment]
Hey @discotest,
Instead of using tzkt api. You can setup a selective indexer, that will give control over the data. You can check out [dipdup](https://dipdup.net/), [tutorial](https://www.youtube.com/watch?v=K-1s6fCBegc&t=340s&ab_channel=BakingBad).

**Comment by discotest** [comment]
Hey @NishantChandla , so, can't I use a method like this? (From a cloned minted contract I deployed from your tutorial)
https://api.hangzhounet.tzkt.io/v1/bigmaps/95470/keys?limit=10000&value.author=tz1M9rpKM8spkNMgnrAoxEdjug9B14ZkRkZc _(  but using a *${dynamic wallet}* )_

Or if the data queried by the call you provided in the tutorial already fetches the "authors" like **author.data**, can we work with it?

I wonder how it would fit the template. Any ideas? 
If you could throw some really simple code here I'd appreciate so much, integrating a profile page!

I imagine a merge between the Home,js page layout and the dynamic ID Show.js routing logic. 
Any idea how to only display the items of a single creator on the cards, also on a page like /profile/tz1... ?



Thanks a lot, master! धन्यवाद
